name: MovieApp CI/CD

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    strategy:
      matrix:
        environment:
            - production

    runs-on: ubuntu-latest

    steps:
    - name: Checkout MovieApp
      uses: actions/checkout@v2

    - name: Configure .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.125

    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release
